on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Set up a MySQL service on the GitHub server.
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: financedb
          MYSQL_USER: admin
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -prootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Give permission to Maven Wrapper
        run: chmod +x ./mvnw

      - name: 4. Ejecutar los tests
        env:
          # Environment variable so Spring context loads correctly
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/financedb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        run: ./mvnw clean test